[package]
name = "e621_downloader"
version = "1.5.6"
authors = ["MightyChubz <theradcast16@gmail.com>"]
edition = "2018"

[dependencies]
base64-url = "1.2.0"
dialoguer = "0.6.2"
indicatif = "0.14.0"
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
serde = { version = "1.0.111", features = ["derive"]}
serde_json = "1.0.55"
failure = "0.1.8"