[package]
name = "e621_downloader"
version = "1.1.3"
authors = ["MightyChubz <theradcast16@gmail.com>"]
edition = "2018"

[dependencies]
pbr = "1.0.1"
reqwest = "0.9.18"
serde = { version = "1.0.94", features = ["derive"]}
serde_json = "1.0.40"
chrono = "0.4.7"
failure = "0.1.5"