[package]
name = "e621_downloader"
version = "1.5.6"
authors = ["MightyChubz <theradcast16@gmail.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.5.0"
indicatif = "0.13.0"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0.44"
failure = "0.1.6"