[package]
name = "e621_downloader"
version = "1.6.1"
authors = ["McSib <mcsibsart@gmail.com>"]
edition = "2018"

[dependencies]
base64-url = "1.4.8"
indicatif = "0.15.0"
reqwest = { version = "0.11.0", features = ["blocking", "json"] }
serde = { version = "1.0.118", features = ["derive"]}
serde_json = "1.0.61"
failure = "0.1.8"