[package]
name = "e621_downloader"
version = "1.7.1"
authors = ["McSib <mcsibsart@gmail.com>"]
edition = "2021"

[dependencies]
base64-url = "1.4.13"
indicatif = "0.17.0-rc.6"
dialoguer = "0.10.0"
console = "0.15.0"
log = "0.4.14"
simplelog = "0.11.2"
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
failure = "0.1.8"
