[package]
name = "e621_downloader"
version = "1.7.0"
authors = ["McSib <mcsibsart@gmail.com>"]
edition = "2018"

[dependencies]
base64-url = "1.4.8"
indicatif = "0.15.0"
dialoguer = "0.7.1"
console = "0.14.0"
log = "0.4.14"
simplelog = "0.9.0"
reqwest = { version = "0.11.0", features = ["blocking", "json"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
failure = "0.1.8"
