[package]
name = "e621_downloader"
version = "1.7.1"
authors = ["McSib <mcsibsart@gmail.com>"]
edition = "2021"

[dependencies]
base64-url = "1.4.13"
indicatif = "0.17.0-rc.10"
dialoguer = "0.10.1"
console = "0.15.0"
log = "0.4.17"
simplelog = "0.12.0"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
failure = "0.1.8"
