[package]
name = "e621_downloader"
version = "0.1.0"
authors = ["MightyChubz <theradcast16@gmail.com>"]
edition = "2018"

[dependencies]
indicatif = "0.11.0"
reqwest = "0.9.12"
serde = { version = "1.0.89", features = ["derive"]}
serde_json = "1.0.39"
chrono = "0.4.6"