[package]
name = "e621_downloader"
version = "1.2.3"
authors = ["MightyChubz <theradcast16@gmail.com>"]
edition = "2018"

[dependencies]
pbr = "1.0.2"
reqwest = "0.9.24"
serde = { version = "1.0.103", features = ["derive"]}
serde_json = "1.0.44"
chrono = "0.4.10"
failure = "0.1.6"