name: Rust

on:
  push:
    branches: [ active ]
  pull_request:
    branches: [ active ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  windows_build:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  mac_build:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - uses: actions-rs/cargo@v1.0.1
      with:
        toolchain: nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
