name: Rust

on:
  push:
    branches: [ active ]
  pull_request:
    branches: [ active ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose

  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose

  mac_build:
    name: Mac Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
    
